# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rand = "0.8.5"